version: '3.9'

networks:
  paymentsNet:
    driver: bridge

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - paymentsNet

  db:
    image: postgres:latest
    ports:
       - "5432:5432"
    networks:
      - paymentsNet
    hostname: databaseOrders
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
